[package]
name = "hyperminhash"
version = "0.1.0"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
metrohash = "1.0"

[dev-dependencies]
rand = "0.6"
